name: validate
on: 
  workflow_dispatch:
  push:
    tags-ignore:
      - '*'
    branches-ignore:
      - '**'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - '**'
      - 'release/**'
      - 'main'
    paths:
      - '.github/workflows/*'
jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: sleep command 80 seconds
        run: echo "Sleeping for 80 secondss ...." && sleep 80
      - name: Deploy project
        run: echo "Deploying..."
